export const cartContent = {
  continueShopping: "Continue shopping",
  emptyTitle: "Your cart is empty",
  emptyDescription: "Explore our robotics products and add the systems you want to discuss with our team.",
  cartTitle: "Your cart",
  product: "Product",
  quantity: "Quantity",
  total: "Total",
  subtotal: "Subtotal",
  remove: "Remove",
  orderNote: "Add a note to your order",
  specialInstructions: "SPECIAL INSTRUCTIONS",
  quote: "Quote summary",
  download: "Download",
  copy: "Copy",
  facebook: "Messenger",
  checkout: "Checkout",
  recentlyViewed: "Recently viewed",
} as const;
